spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kavakpostgre
    username: kavak
    password: kavak
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
