spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ocampopostgre?options=-c%20TimeZone%3DUTC
    username: ocampo
    password: ocampo
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
